[workspace]
members = ["crates/core", "crates/player"]
resolver = "2"
exclude = ["crates/renderer-notan"]

[patch.crates-io]
fontkit = { git = "https://github.com/alibaba/font-toolkit", rev = "9f71345" }
