[package]
edition = "2021"
name = "lottie-ast"
version = "0.1.0"

[dependencies]
euclid = "0.22.7"
serde_json = "1.0.79"
serde_repr = "0.1.7"

[dependencies.serde]
features = ["derive"]
version = "1.0.136"

[dev-dependencies]
serde_path_to_error = "0.1.7"
