[package]
edition = "2021"
name = "lottie-renderer-bevy"
version = "0.1.0"

[dependencies]
bevy_diagnostic = "0.7.0"
bevy_prototype_lyon = "0.5.0"
flo_curves = "0.6.1"
log = "0.4.17"
ordered-float = "3.0.0"
infer = "0.8.1"

bevy = { version = "0.7.0", features = ["bevy_audio", "mp3", "flac", "wav"] }
wgpu = "0.12.0"
image = { version = "0.24.2", default-features = false, features = [ "png" ] }

[dependencies.bevy_tweening]
git = "https://github.com/zimond/bevy_tweening"
rev = "c605878"

[dependencies.lottie-core]
path = "../core"
