[package]
edition = "2021"
name = "lottie-renderer-bevy"
version = "0.1.0"

[dependencies]
bevy_diagnostic = "0.7.0"
bevy_prototype_lyon = "0.5.0"
flo_curves = "0.6.1"
log = "0.4.17"

[dependencies.bevy]
version = "0.7.0"

[dependencies.bevy_tweening]
git = "https://github.com/zimond/bevy_tweening"
rev = "c605878"

[dependencies.lottie-core]
path = "../core"
