[package]
name = "renderer-notan"
version = "0.1.0"
edition = "2021"

[dependencies]
lottie-core = { version = "0.1.0", path = "../core" }
notan = { git = "https://github.com/Nazariglez/notan", branch = "develop", version = "0.5.0" }
