[package]
edition = "2021"
name = "lottie-player"
version = "0.1.0"

[dependencies]
bevy = "0.7.0"

[dependencies.clap]
features = ["derive"]
version = "3.1.10"

[dependencies.lottie-core]
path = "../core"

[dependencies.lottie-renderer-bevy]
path = "../renderer-bevy"
