[package]
edition = "2021"
name = "lottie-player"
version = "0.1.0"

[dependencies]
bevy = "0.7.0"
bevy-inspector-egui = "0.11.0"
bevy_prototype_debug_lines = { git = "https://github.com/Toqozz/bevy_debug_lines" }
env_logger = "0.9.0"
bevy_egui = "0.14.0"

[dependencies.clap]
features = ["derive"]
version = "3.1.10"

[dependencies.lottie-core]
path = "../core"

[dependencies.lottie-renderer-bevy]
path = "../renderer-bevy"
