name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        # https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md
        sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
          
    - name: Build
      run: cargo build --manifest-path crates/core/Cargo.toml
      
    - name: Run tests
      run: cargo test --manifest-path crates/core/Cargo.toml
